grammars/css.cson
spec/css-spec.coffee

This pull request fixes an error reported in #33:
```css
/** Comment */ @media (max-height: 40em){
}
```
See the [fix in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-css%2Ffa3c1a4b7c52c59bf1e7258095c1a6bc33d6273c%2Fgrammars%2Fcss.cson&grammar_text=&code_source=from-text&code_url=&code=%2F**+Comment+*%2F+%40media+%28max-height%3A+40em%29{%0D%0A%0D%0A}).

Fix error with @media preceeded by a comment

---

grammars/css.cson

This PR adds a list of deprecated CSS2 System colors. These were deprecated in CSS color module level 3. Follows on from a similar PR to the `language-sass` repo.

Add deprecated CSS2 System colors

---

grammars/css.cson
package.json
spec/css-spec.coffee

fixed an issue with this grammar not supporting block-comments after unterminated property values

Added support for inline block comment

---

grammars/css.cson
spec/css-spec.coffee

@hansottowirtz hasn't been responsive on #64 for quite a while, so I decided to take over.

Rewrite custom element

---

grammars/css.cson
spec/css-spec.coffee

One reason to change is that right now `}` can be scoped as
```
['source.css', 'meta.property-list.css', 'meta.property-value.css', 'punctuation.section.property-list.end.css']
```
or
```
['source.css', 'meta.property-list.css', 'punctuation.section.property-list.end.css']
```
which is unpredictable, depending on whether a `;` is present.

Fix property value so surrounding punctuation are not scoped as value

---

grammars/css.cson
spec/css-spec.coffee

This is an attempt to start improving the support for CSSNext: https://github.com/atom/language-css/issues/51
It's also my first time with a language package so please tell me if I did something wrong.

Add support for custom properties

---

grammars/css.cson
spec/css-spec.coffee

The scope "meta.language-ranges.css" seems like unnecessary complexity, is it ok to remove it?

Improve the support for :lang()

---

grammars/css.cson
spec/css-spec.coffee

Self-explanatory. Adds `firstLineMatch` support for Vim/Emacs modelines.

Add support for Emacs/Vim modelines

---

grammars/css.cson
spec/css-spec.coffee

While linking the `language-css` package's keyword lists to Less, I became stuck on this spec:
~~~coffeescript
it "parses property names distinctly from property values with the same text", ->
{tokens} = grammar.tokenizeLine("{left:left;}")
~~~
I tried finding a solution which didn't involve repeating the CSS grammar's keywords, but failed. This seems to be the cleanest answer: a CSS selector ending with a semicolon or close bracket isn't valid anyway, so this seems safe to do.
(I hope I explained this correctly..)

Amend patterns to facilitate embedding within Less

---

grammars/css.cson
spec/css-spec.coffee

This is a fix for something I overlooked while working on #99 - the terminating pattern for nested `@at-rules` will also stop at a `}` character which precedes the original match:
~~~css
h1 { }@media  {   } /* Not matched */
h1 { } @media {   } /* Matched */
~~~
N/A. This is a bugfix.
It'll fix #107 and appease users with sloppy coding habits.
N/A
N/A

Fix #107: @at-rules not matched if preceded by closing brace

---

grammars/css.cson

Added -webkit-keyframes, -moz-keyframes, -o-keyframes, and -ms-keyframes to begin and patterns regex for ```@keyframes``` in grammar.cson, allowing these to follow the same syntax highlighting rules as ```@keyframes```.
Fix #110
Applies ```@keyframes``` at-rule syntax highlighting correctly if vendor prefixes are used
#99 Add support for literally every modern CSS feature

Fix #110: Recognize keyframes at-rule with vendor prefixes

---

grammars/css.cson

**Before:**
Numerous **Nuclide** users are complaining already with the invalid CSS highlighting
matching `.no-highlight/abc {` yielding an invalid highlight marker.
**After:**
It highlights correctly:
I have no idea!

Fix valid identifier/identified error highlighting

---

grammars/css.cson

Exactly what it looks like.
Fixes atom/language-sass#211, now that language-sass is using CSS's number patterns.

Add support for the `fr` unit

---

grammars/css.cson

Adds syntax coloring for three grid keywords: upleft, downleft, and downright. The keyword "upright" already had syntax highlighting, so this adds it to the other three. Fixes #120. The results can be seen here: http://imgur.com/q902Vk5
More cohesive syntax highlighting.
Fixes #120

Add coloring to grid keywords

---

grammars/css.cson

language-css is not highlighting focus-within, which is already implemented in Chrome 60.
This change will make overall experience using language-css with focus-within property better (adds highlighting)
It will be clear that this is accepted attribute

Added focus-within pseudo-class highlight

---

grammars/css.cson

This PR has absolutely no bearing on Atom: it's strictly for the benefit of VSCode and GitHub, both of which are using this grammar to highlight CSS code. I'm still not sure how or when the discrepancy started happening: I remember this pattern worked for other grammars I worked on... 😞
Anyway, to verify that this fix worked, I installed VSCode in a VirtualBox installation, and modified the VSCode version of the grammar (which was located at `C:\Program Files\Microsoft VS Code\resources\app\extensions\css\syntaxes`). Here's the result:
It'll fix highlighting on GitHub:
~~~css
#testcase::before {
content: 'long string\
using line continuation';
}
~~~
None. Atom's tests passed without complaint.
Fixes atom/language-css#123

Fix line continuation in other TMCG implementations

---

grammars/css.cson

This change adds support for `font-display` and its possible values.
None.
Syntax highlight for `font-display`.
None.
Fixes #125.

issue-125: Add support for font-display

---

grammars/css.cson

Some parameters inside pseudo class **dir** haven't been colorized. It's trivial but it should be fixed.
The reason is the mistypo of pattern name and I just fixed it.
None
We can see pattern colorizing inside dir pseudo class as intended.
None
None

Fix mistyped pattern name in css syntax

---

grammars/css.cson

Fixes #135 by updating the list of CSS property keywords.
Changes should be self-explanatory.
/cc @50Wliu

Add "space-evenly" to the property-keyword list

---

grammars/css.cson
spec/css-spec.coffee

This gives some basic highlighting to unknown at-rules. The rules are modeled after `@media`.
For example,
```css
@some-rule () {
}
```
Will now receive correct highlighting on
- `@some-rule` as `keyword.control.at-rule.css`
- `some-rule` as `punctuation.definition.keyword.css`
- Everything between `{` and `}` is tokenized as normal css
- There is no tokenization between `(` and `)`, as we don't know the argument format for the unknown at rule
Before:
After:
Spec: https://www.w3.org/TR/css-syntax-3/#consume-an-at-rule
Related: https://github.com/Microsoft/vscode-css-languageservice/issues/51
Motivation: Pre-processors that define custom at-rules, for example https://github.com/css-modules/postcss-icss-values
Better syntax highlighting of unknown css rules.
None. …

Handle syntax highlighting of custom at-rules for Microsoft/vscode-css-languageservice#51

---

grammars/css.cson
spec/css-spec.coffee

The following properties were not being tagged as supported properties:
- `row-gap`
- `place-items`
- `place-self`
- `place-content`
This pull request fixes this issue by adding the above-mentioned properties to the supported
properties Regex Pattern.
None
All the new grid properties will now be the same colour as other supported properties.
None
None

Add grid properties that were not being recognized as supported

---

grammars/css.cson
spec/css-spec.coffee

As detailed in #163, properties should not be scoped as `invalid.deprecated` easily to cause red syntax highlighting meant for syntax errors.
n/a
Editors still using the TextMate grammar (including older versions of Atom) would be able to use deprecated media queries without seeing the red flagging (they might be targeting old browsers so their usage would be valid).
n/a
- https://github.com/atom/language-css/issues/163
- https://github.com/microsoft/vscode/issues/62515

Fix #163 by not marking media properties as `invalid.deprecated`

---

grammars/css.cson

This adds support for the following generic font families, which were added to the [CSS Fonts Module Level 4](https://drafts.csswg.org/css-fonts-4/):
- `system-ui`
- `ui-monospace`
- `ui-rounded`
- `ui-sans-serif`
- `ui-serif`
Not applicable.
Atom users will see these values properly syntax-highlighted like they do with `serif`, `sans-serif`, and other generic font family keyword values.
While [`system-ui` is well-supported](https://caniuse.com/#feat=font-family-system-ui), `ui-monospace`, `ui-rounded`, `ui-sans-serif`, and `ui-serif` are newer and [less supported](https://caniuse.com/#feat=extended-system-fonts).
I couldn’t find any.

Add generic system font families

---

spec/css-spec.coffee

* ❌ All new code requires tests to ensure against regressions. **Not needed here due there's no change in implementation**
Fix typo in "highlight deprecated combinators" spec, Replaces "combintors" by "combinators"
it seems that there's no alternate design
Improve text quality and reduce anxiety of people who suffer OCD
None
Nope

Fix typo in "highlight deprecated combinators" spec

---

grammars/css.cson

This change only adds some missing values for the `scroll-snap-type` property.
Does not apply.
Adds syntax highlighting for the missing values.
Does not apply.
Closes #148

Add missing scroll-snap-type values

---

grammars/css.cson

Add `justify-self` and `justify-items`
https://www.w3.org/TR/css-grid-1/#row-align
Syntax highlighting of this properties.
None.
Fixes #131

Add justify-self and justify-items grid properties

---

grammars/css.cson

This PR addresses a specificity issue in the tag-names matcher which causes a bug in language-less.
Currently, the `tag-names` matcher ends with a postive lookahead of simply a single colon (among other things) after any of the valid tag names is found. The reason this is a problem is because some tag names are also property names (e.g. `cursor`, `font`, `content`, etc).
To fix this, all that needed to happen is a slight adjustment to the regex to increase the specificity to match only colons followed by a non-space.
There really is no other way I can think of other than having the selector match a colon followed by a non-space because of all the possibilities with pseudo selectors, child selectors, etc. Because of that, there will still be a mistake in some situations where the user …

adjust tag-names match to fix downstream issue in language-less

---

grammars/css.cson
spec/css-spec.coffee

Adds support for vendor prefixes -ms- and -o- to the viewport at-rule
No alternatives considered, I think I have fixed it appropriately within the architecture.
Css grammar support will reflect viewport syntax used in older browsers.
...none?
fixes #176

Add in @-ms-viewport and @-o-viewport to CSS grammar

---

grammars/css.cson

Enable syntax hilighting for the `:focus-visible` CSS pseudo-class
Support this relatively used pseudo-class (Compatible with latest Chrome, Firefox, Edge, Opera as of writing)
Ref. https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
I can't think of one ;-)

Add :focus-visible pseudoclass

---

grammars/css.cson

Adds the following properties to the property list:
- [margin-block](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block)
- [margin-inline](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline)
- [padding-block](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block)
- [padding-inline](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline)
The corresponding `(margin|padding)-(block|inline)-*` properties are already present; these properties are shorthands for them.
N/A
Correct highlighting behavior in VS Code
I have …

Add missing margin/padding properties

---

grammars/css.cson

docs : 
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb()
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lab()
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch()
Intention is to have syntax highlighting in the same fashion as `rgb`

Add new color functions to CSS grammar

---

grammars/css.cson

This PR:
- adds `min`, `max`, and `clamp` functions
- adds `accent-color`, `color-scheme`, `margin-block`, `margin-inline`, `padding-block`, `padding-inline`, and `text-underline-offset` properties
- adds `light`, and `dark` property values (for `color-scheme`)
Correctly syntax-highlight the added functions and properties.
fixes #186

Add missing min/max/clamp functions and some properties
